#ifndef TRISNGULATIONLIB_GLOBAL_H
#define TRISNGULATIONLIB_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(TRISNGULATIONLIB_LIBRARY)
#  define TRISNGULATIONLIBSHARED_EXPORT Q_DECL_EXPORT
#else
#  define TRISNGULATIONLIBSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // TRISNGULATIONLIB_GLOBAL_H
